# Generated by Django 3.1 on 2021-03-25 00:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import notificacao.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agrupamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(max_length=255)),
                ('status', models.BooleanField(default=False, verbose_name='lida')),
                ('data', notificacao.models.CustomDateTimeField(default=django.utils.timezone.now)),
                ('id_agrupamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agrupamento', to='agrupamentos.agrupamento')),
            ],
        ),
    ]
