# Generated by Django 3.1 on 2021-03-25 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fazenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agrupamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(max_length=255, unique=True)),
                ('fazenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fazenda.fazenda')),
            ],
        ),
    ]
