# Generated by Django 3.1 on 2021-05-22 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fazenda', '0001_initial'),
        ('agrupamentos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agrupamento',
            old_name='identificacao',
            new_name='descricao',
        ),
        migrations.AlterField(
            model_name='agrupamento',
            name='fazenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agrupamento', to='fazenda.fazenda'),
        ),
    ]
