# Generated by Django 3.1 on 2021-03-25 00:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import historico.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('historico_tipo', '0001_initial'),
        ('animais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(max_length=255)),
                ('notificacao', models.BooleanField(default=False, verbose_name='lida')),
                ('data', historico.models.CustomDateTimeField(default=django.utils.timezone.now)),
                ('cod_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historico_tipo.historico_tipo')),
                ('id_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='animais.animal')),
            ],
        ),
    ]
